[project]
name = "convow2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "flask>=3.1.3",
    "flask-sock>=0.7.0",
    "numpy>=2.4.2",
    "requests>=2.32.5",
]
